server:
  port: 9999
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YingjiaZhang/spring-cloud-config-repo
          username: zhyingjia@163.com