server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie-fegin-hystrix-fallback-factory

eureka:
  client:
    service-url:
      default-zone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true


