server:
  port: 9999
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YingjiaZhang/spring-cloud-config-repo
          username:
          password:
          clone-on-start: true
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
# 设置 loglevel 为 debug, 可以打印config server 请求 git repo 的细节，
# 能够帮助我们更好地理解config server 的git仓库的配置，便于快速定位问题
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.boot: DEBUG
management:
  security:
    enabled: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
